title: Deconstructing Deep learning
description: Making a Deep Learning library from scratch in Julia and documenting it the whole way!
theme: jekyll-theme-minimal
author: Subhaditya Mukherjee
plugins:
  - jekyll-feed
  - jekyll-analytics
  - jekyll-katex
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-122655566-1          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

markdown: kramdown

kramdown:
  math_engine: katex

katex:
  js_path: "{{ Gem::lib_path }}/assets/js"  # Path used to search for katex.min.js
  rendering_options:
    # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
    throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
    error_color: "#cc0000"                  # errorColor
