title: Deconstructing Deep learning
description: Digging into deep learning books, papers and code
theme: jekyll-theme-minimal
author: Subhaditya Mukherjee
plugins:
  - jekyll-feed
  - jekyll-toc
  - jekyll-seo-tag
  
markdown: kramdown
github: [metadata]
minima:
  skin: dark

