title: Deconstructing Deep learning
description: Digging into deep learning books, papers and code
theme: jekyll-theme-minimal
author: Subhaditya Mukherjee
plugins:
  - jekyll-feed
  - jekyll-analytics
  - jekyll-toc
  - jekyll-seo-tag
  
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-122655566-2          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

markdown: kramdown
github: [metadata]
minima:
  skin: dark
