title: Deconstructing Deep learning
description: Making a Deep Learning library from scratch in Julia and documenting it the whole way!
theme: jekyll-theme-minimal
author: Subhaditya Mukherjee
plugins:
  - jekyll-feed
  - jekyll-analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-122655566-1          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

markdown: kramdown
github: [metadata]
